name:                largest-rectangle
version:             0.1.0.0
github:              "maruks/largest-rectangle"
license:             BSD3
author:              "Maris Orbidans"
maintainer:          "maris.orbidans@gmail.com"
copyright:           "2019 Maris Orbidans"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maruks/largest-rectangle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  largest-rectangle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - largest-rectangle

tests:
  largest-rectangle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - largest-rectangle
    - hspec
    - QuickCheck
